theme: jekyll-theme-slate
title: Welcome to the personal page of Lena Hahn
description: What you will find here is a collection of all things related to my ever-evolving interests
description: migration • urban policy • conflict mapping • borders • and the Wild, Wild West
![Zion © National Park Service](https://www.nps.gov/common/uploads/banner_image/imr/homepage/0047D4F0-1DD8-B71B-0B56566586F793FA.jpg)
