theme: jekyll-theme-slate
title: Welcome to the personal homepage of Lena Hahn
description: What you will find here is a collection of all things related to my ever-evolving interests, which include migration, urban policy, conflict mapping and security issues. My main geographic focus is Europe, the MENA region and the Far East.
